from app.extensions import db

class EMZRecord(db.Model):
    __tablename__ = 'emz_records'
    __table_args__ = {'schema': 'general'}  # якщо таблиця в схемі general

    id = db.Column(db.Integer, primary_key=True, server_default=db.text("nextval('general.emz_records_id_seq'::regclass)"))
    report_year = db.Column(db.BigInteger)
    report_month = db.Column(db.BigInteger)
    emz_type = db.Column(db.Text)
    emz_id = db.Column(db.Text)
    submitted_to_esoz = db.Column(db.Text)
    executor_position = db.Column(db.Text)
    executor_name = db.Column(db.Text)
    service_location = db.Column(db.Text)
    referral_type = db.Column(db.Text)
    referral_org_edrpou = db.Column(db.Text)
    referral_doctor_position = db.Column(db.Text)
    episode_id = db.Column(db.Text)
    episode_type = db.Column(db.Text)
    episode_start = db.Column(db.Text)
    dz_start = db.Column(db.Text)
    episode_end = db.Column(db.Text)
    treatment_duration_days = db.Column(db.BigInteger)
    main_diagnosis = db.Column(db.Text)
    main_diagnosis_validity_status = db.Column(db.Text)
    main_diagnosis_clinical_status = db.Column(db.Text)
    additional_diagnoses = db.Column(db.Text)
    disproved_additional_diagnoses = db.Column(db.Text)
    interventions = db.Column(db.Text)
    interaction_class = db.Column(db.Text)
    priority = db.Column(db.Text)
    interaction_type = db.Column(db.Text)
    hospitalization_reason = db.Column(db.Text)
    treatment_result = db.Column(db.Text)
    patient_unique_code = db.Column(db.Text)
    patient_has_declaration = db.Column(db.Text)
    patient_gender = db.Column(db.Text)
    patient_weight_grams = db.Column(db.Text)
    patient_age_days = db.Column(db.Text)
    patient_age_years = db.Column(db.Text)
    adsg = db.Column(db.Text)
    service_package = db.Column(db.Text)
    service_number = db.Column(db.Text)
    tariff = db.Column(db.Text)
    payment_amount = db.Column(db.Text)
    included_in_statistics = db.Column(db.Text)
    included_in_report = db.Column(db.Text)
    error_comment = db.Column(db.Text)
    error_details = db.Column(db.Text)
    mismatch_details = db.Column(db.Text)
    grouping_conflicts = db.Column(db.Text)
    nszu_package_review_details = db.Column(db.Text)
    additional_comments = db.Column(db.Text)
    nszu_review_date = db.Column(db.Text)
